name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL_MAIN }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL_DEV }}" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Deploy to Amplify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm install -g @aws-amplify/cli@latest
          amplify init --no-verify
          amplify push
          amplify publish
