name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL_MAIN }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL_DEV }}" >> $GITHUB_ENV
          fi

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Deploy to Amplify Hosting
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths /index.html
